############################################################
# Dockerfile to build docker scrape for docker interview
# Based on Ubuntu
############################################################

# Base image ubuntu, specify 14.04
FROM ubuntu

MAINTAINER Brian Hou

RUN apt-get update